# Plex Configuration File
# For documentation, please visit: https://plex.us.org

server:
  name: "Plexus"

  # Placeholders
  # %mcversion% - The Velocity Version (i.e. 3.5.0-SNAPSHOT)
  # %servername% - The name provided above
  # %randomgradient% - Creates a random gradient every ping of two random colors for the whole string
  # Supports MiniMessage strings, no legacy & and §
  motd:
    - "%randomgradient%%servername% - %mcversion%"
    - "Another motd"
  colorize_motd: false

  # Enables debug messages
  debug: false

  # Due to game code only supporting legacy color codes for
  # player samples and not components, you may only use legacy section-sign
  # color codes or & here for colors.
  sample:
    - "example"
    - "example"

  # Adds this amount to the current player count
  add_player_count: 0

  # The max player count will always display as +1 more than the player count
  plus_one_max_count: true
